version: '3.3'

services: # containers
  web:
    depends_on:
      - kubenews-db
    image: raphavtorres/kube-news:v1
    ports:
      - 8888:8080
    networks:
      - kube-news-net
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_HOST: kubenews-db

  kubenews-db:
    image: postgres
    container_name: kubenews-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: kubenews
    ports:
      - 4242:5432
    volumes: 
      - postgres-vol:/var/lib/postgresql/data/
    networks:
      - kube-news-net

volumes:
  postgres-vol:

networks:
  kube-news-net:
    driver: bridge